namespace OneKey;

/// <summary>
/// 자동 실행 등록·지우기 PowerShell 명령(0.3.105 시험 B "내장형", 2026-10-06 사용자). tools\*.cmd 의 -Command 내용을 그대로 옮겼다
/// (스크립트를 바꾸면 이 파일도 같이 고친다). 끝에 결과를 보고 Enter 로 닫게 한 줄만 더했다.
/// 1Key 는 powershell.exe 를 이 명령으로 실행만 한다(-EncodedCommand 를 쓰지 않는다 — 숨긴 명령처럼 보이지 않게).
/// 0.3.116 시험 C(사용자 2026-10-07 — 등록이 3~5초 걸림): 관리자 작업 등록·지우기를 ScheduledTasks 모듈(Get-/New-/Register-/Unregister-ScheduledTask,
/// 불러오는 데만 약 1.3초) 대신 PowerShell 안의 작업 스케줄러 COM(Schedule.Service, 약 0.06초)으로 — 같은 작업(이름·설명·로그온 트리거·
/// 대화형 토큰·가장 높은 권한·배터리 조건 없음·시간 제한 없음·새 인스턴스 무시·동작 하나). 설치 폴더 tools\*.cmd 는 아직 예전 명령 그대로
/// (Defender 가 다시 탐지하면 되돌리고 창 멈춤 없애기 + 지우기 때 확인 건너뛰기로 간다). 실패 사유 파일 이름도 고침(예전에는 %TEMP% 옆
/// "TempKey-…" 에 써서 1Key 가 읽지 못했다).
/// </summary>
internal static class AutostartScripts
{
    public const string RegisterAdmin = @"$ErrorActionPreference = 'Stop'; try { $identity = [Security.Principal.WindowsIdentity]::GetCurrent(); $principal = New-Object Security.Principal.WindowsPrincipal($identity); if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { throw 'Right-click this CMD file and select Run as administrator. Use your usual Windows account.' }; $target = Join-Path $env:LOCALAPPDATA 'Programs\1Key\1Key.exe'; if (-not (Test-Path -LiteralPath $target -PathType Leaf)) { throw ('1Key executable not found: ' + $target) }; $sid = $identity.User.Value; $name = '1Key-AdminStartup-' + $sid; $service = New-Object -ComObject Schedule.Service; $service.Connect(); $folder = $service.GetFolder('\'); $old = $null; try { $old = $folder.GetTask($name) } catch { }; if ($old) { throw ('Task already exists; no changes made: ' + $name) }; $def = $service.NewTask(0); $def.RegistrationInfo.Description = 'Start installed 1Key at sign-in with highest available privileges'; $def.Principal.UserId = $sid; $def.Principal.LogonType = 3; $def.Principal.RunLevel = 1; $def.Settings.DisallowStartIfOnBatteries = $false; $def.Settings.StopIfGoingOnBatteries = $false; $def.Settings.ExecutionTimeLimit = 'PT0S'; $def.Settings.MultipleInstances = 2; $trigger = $def.Triggers.Create(9); $trigger.UserId = $sid; $action = $def.Actions.Create(0); $action.Path = $target; $action.WorkingDirectory = (Split-Path -Parent $target); [void]$folder.RegisterTaskDefinition($name, $def, 2, $null, $null, 3); Write-Host ('Registered: ' + $name); Write-Host ('Program: ' + $target); Write-Host 'The task will run at the next sign-in. It has not been started now.'; exit 0 } catch { [IO.File]::WriteAllText((Join-Path $env:TEMP '1Key-autostart-result.txt'), [string]$_.Exception.Message); exit 1 }";

    public const string RegisterUser = @"$ErrorActionPreference = 'Stop'; try { $target = Join-Path $env:LOCALAPPDATA 'Programs\1Key\1Key.exe'; if (-not (Test-Path -LiteralPath $target -PathType Leaf)) { throw ('1Key executable not found: ' + $target) }; $startup = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs\Startup'; [void][System.IO.Directory]::CreateDirectory($startup); $link = Join-Path $startup '1Key.lnk'; if (Test-Path -LiteralPath $link) { throw ('Shortcut already exists. Remove it first if you want to replace it: ' + $link) }; $shell = New-Object -ComObject WScript.Shell; $shortcut = $shell.CreateShortcut($link); $shortcut.TargetPath = $target; $shortcut.WorkingDirectory = Split-Path -Parent $target; $shortcut.IconLocation = $target + ',0'; $shortcut.Description = 'Start 1Key at Windows sign-in'; $shortcut.Save(); Write-Host ('Created: ' + $link); exit 0 } catch { [IO.File]::WriteAllText((Join-Path $env:TEMP '1Key-autostart-result.txt'), [string]$_.Exception.Message); exit 1 }";

    public const string Remove = @"$ErrorActionPreference = 'Stop'; try { $identity = [Security.Principal.WindowsIdentity]::GetCurrent(); $sid = $identity.User.Value; $name = '1Key-AdminStartup-' + $sid; $target = Join-Path $env:LOCALAPPDATA 'Programs\1Key\1Key.exe'; $link = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs\Startup\1Key.lnk'; $service = New-Object -ComObject Schedule.Service; $service.Connect(); $folder = $service.GetFolder('\'); $task = $null; try { $task = $folder.GetTask($name) } catch { }; if ($task) { $principal = New-Object Security.Principal.WindowsPrincipal($identity); if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { throw 'Right-click this CMD file and select Run as administrator, using your usual Windows account. Nothing has been removed.' }; $def = $task.Definition; if ($def.RegistrationInfo.Description -ne 'Start installed 1Key at sign-in with highest available privileges' -or $def.Actions.Count -ne 1 -or $def.Actions.Item(1).Path -ne $target) { throw ('Task differs from the companion registration script; not removed: ' + $name) } }; if (Test-Path -LiteralPath $link) { $shell = New-Object -ComObject WScript.Shell; $shortcut = $shell.CreateShortcut($link); if ($shortcut.TargetPath -ne $target) { throw ('Shortcut points to another program; not removed: ' + $link) } }; if ($task) { $folder.DeleteTask($name, 0); Write-Host ('Removed task: ' + $name) } else { Write-Host 'No companion startup task found.' }; if (Test-Path -LiteralPath $link) { Remove-Item -LiteralPath $link -Force; Write-Host ('Removed shortcut: ' + $link) } else { Write-Host 'No companion startup shortcut found.' }; Write-Host 'Program files, settings, and the running application were not changed.'; exit 0 } catch { [IO.File]::WriteAllText((Join-Path $env:TEMP '1Key-autostart-result.txt'), [string]$_.Exception.Message); exit 1 }";
}
