# Generates src/OneKey/Strings.g.cs from src/OneKey/i18n/strings.tsv (UTF-8).
# One row per text: key <TAB> ko <TAB> en <TAB> zh-Hans <TAB> ja <TAB> vi. Lines starting with '#' are section comments.
# Checks (build fails on error):
#   - every key is unique and looks like "area.name" (letters/digits, one or more dots)
#   - ko and en are present for every key
#   - every non-empty translation uses exactly the same {placeholders} as ko
#   - only \n and \\ escapes; no tabs inside a cell
# An empty zh-Hans/ja/vi cell falls back to en (then ko) and is listed as a warning.
# Accessors: T.AreaName (no placeholders) or T.AreaName(object a, object b) (placeholders in order of first use in ko).
param(
    [string]$Tsv = (Join-Path $PSScriptRoot '..\..\src\OneKey\i18n\strings.tsv'),
    [string]$Out = (Join-Path $PSScriptRoot '..\..\src\OneKey\Strings.g.cs')
)
$ErrorActionPreference = 'Stop'
$utf8 = New-Object System.Text.UTF8Encoding($false)
$lines = [System.IO.File]::ReadAllLines((Resolve-Path $Tsv), [System.Text.Encoding]::UTF8)
$langs = @('ko', 'en', 'zh-Hans', 'ja', 'vi')
$errors = New-Object System.Collections.Generic.List[string]
$warnings = New-Object System.Collections.Generic.List[string]
$rows = New-Object System.Collections.Generic.List[object]
$seen = @{}

function Get-Holders([string]$s) {
    $list = New-Object System.Collections.Generic.List[string]
    foreach ($m in [regex]::Matches($s, '\{([A-Za-z][A-Za-z0-9]*)\}')) { if (-not $list.Contains($m.Groups[1].Value)) { $list.Add($m.Groups[1].Value) } }
    return ,$list
}
function To-Pascal([string]$key) {
    $sb = New-Object System.Text.StringBuilder
    foreach ($part in $key.Split('.')) { if ($part.Length -gt 0) { [void]$sb.Append([char]::ToUpperInvariant($part[0])).Append($part.Substring(1)) } }
    return $sb.ToString()
}
function To-CSharp([string]$s, [string]$where) {
    # cell escapes: \n (newline) and \\ (backslash). Anything else after a backslash is an error.
    $sb = New-Object System.Text.StringBuilder
    for ($i = 0; $i -lt $s.Length; $i++) {
        $c = $s[$i]
        if ($c -eq '\') {
            if ($i + 1 -lt $s.Length -and ($s[$i + 1] -eq 'n' -or $s[$i + 1] -eq '\')) { [void]$sb.Append('\').Append($s[$i + 1]); $i++; continue }
            $script:errors.Add("${where}: unsupported escape")
            continue
        }
        if ($c -eq '"') { [void]$sb.Append('\"'); continue }
        if ([int]$c -lt 32) { $script:errors.Add("${where}: control character"); continue }
        [void]$sb.Append($c)
    }
    return '"' + $sb.ToString() + '"'
}

$header = $lines[0].TrimStart([char]0xFEFF).Split("`t")
for ($i = 0; $i -lt $langs.Count; $i++) { if ($header[$i + 1] -ne $langs[$i]) { throw "header column $($i + 1) must be $($langs[$i])" } }

for ($n = 1; $n -lt $lines.Length; $n++) {
    $line = $lines[$n]
    if ($line.Length -eq 0 -or $line.StartsWith('#')) { continue }
    $cells = $line.Split("`t")
    $where = "strings.tsv:$($n + 1)"
    # exactly 6 columns: a 7th column (an extra tab typed in Excel, a shifted row) would otherwise be dropped silently (Codex V55-7)
    if ($cells.Count -ne 6) { $errors.Add("${where}: expected 6 columns, got $($cells.Count)"); continue }
    $key = $cells[0]
    if ($key -notmatch '^[a-z][A-Za-z0-9]*(\.[a-z][A-Za-z0-9]*)+$') { $errors.Add("${where}: bad key '$key'"); continue }
    if ($seen.ContainsKey($key)) { $errors.Add("${where}: duplicate key '$key'"); continue }
    $seen[$key] = $true
    $vals = @($cells[1], $cells[2], $cells[3], $cells[4], $cells[5])
    if ($vals[0].Length -eq 0) { $errors.Add("${where}: '$key' has no ko") }
    if ($vals[1].Length -eq 0) { $errors.Add("${where}: '$key' has no en") }
    $holders = Get-Holders $vals[0]
    for ($l = 1; $l -lt 5; $l++) {
        if ($vals[$l].Length -eq 0) { continue }
        $h = Get-Holders $vals[$l]
        $a = ($holders | Sort-Object) -join ','
        $b = ($h | Sort-Object) -join ','
        if ($a -ne $b) { $errors.Add("${where}: '$key' $($langs[$l]) placeholders {$b} differ from ko {$a}") }
    }
    for ($l = 2; $l -lt 5; $l++) {
        if ($vals[$l].Length -eq 0) { $warnings.Add("'$key' has no $($langs[$l]) (falls back to en)"); $vals[$l] = $vals[1] }
    }
    $rows.Add([pscustomobject]@{ Key = $key; Name = (To-Pascal $key); Vals = $vals; Holders = $holders; Where = $where })
}

$names = @{}
foreach ($r in $rows) { if ($names.ContainsKey($r.Name)) { $errors.Add("$($r.Where): '$($r.Key)' maps to the same name as another key ($($r.Name))") } else { $names[$r.Name] = $true } }

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// <auto-generated/>')
[void]$sb.AppendLine('// Generated by tools/i18n/gen-strings.ps1 from src/OneKey/i18n/strings.tsv. Do not edit; edit the TSV.')
[void]$sb.AppendLine("// $($rows.Count) texts; $($warnings.Count) missing translations fall back to en.")
[void]$sb.AppendLine('#nullable enable')
[void]$sb.AppendLine('namespace OneKey;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('internal static partial class T')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine("    public const int Count = $($rows.Count);")
$fields = @('Ko', 'En', 'ZhHans', 'Ja', 'Vi')
for ($l = 0; $l -lt 5; $l++) {
    [void]$sb.AppendLine("    internal static readonly string[] $($fields[$l]) =")
    [void]$sb.AppendLine('    {')
    foreach ($r in $rows) { [void]$sb.AppendLine('        ' + (To-CSharp $r.Vals[$l] "$($r.Where) $($langs[$l])") + ',') }
    [void]$sb.AppendLine('    };')
}
[void]$sb.AppendLine('')
for ($i = 0; $i -lt $rows.Count; $i++) {
    $r = $rows[$i]
    if ($r.Holders.Count -eq 0) {
        [void]$sb.AppendLine("    /// <summary>$($r.Key)</summary>")
        [void]$sb.AppendLine("    public static string $($r.Name) => L.Get($i);")
    } else {
        $params = ($r.Holders | ForEach-Object { "object $_" }) -join ', '
        $pairs = ($r.Holders | ForEach-Object { '"{' + $_ + '}", ' + $_ }) -join ', '
        [void]$sb.AppendLine("    /// <summary>$($r.Key)</summary>")
        [void]$sb.AppendLine("    public static string $($r.Name)($params) => L.Fmt(L.Get($i), $pairs);")
    }
}
[void]$sb.AppendLine('}')

foreach ($w in $warnings) { Write-Host "gen-strings: warning: $w" }
if ($errors.Count -gt 0) {
    foreach ($e in $errors) { Write-Host "gen-strings: error: $e" }
    exit 1
}
$outPath = [System.IO.Path]::GetFullPath($Out)
$text = $sb.ToString()
if (-not (Test-Path $outPath) -or [System.IO.File]::ReadAllText($outPath, [System.Text.Encoding]::UTF8) -ne $text) {
    [System.IO.File]::WriteAllText($outPath, $text, (New-Object System.Text.UTF8Encoding($true)))
    Write-Host "gen-strings: wrote $outPath ($($rows.Count) texts)"
} else { Write-Host "gen-strings: up to date ($($rows.Count) texts)" }
exit 0
